### ISSUE TITLE
Registration fails with email provided

### ISSUE THREAD

**Issue by almereyda** [allmende/docker-matrix#10]
As the identity servers don't seem to provide proper CORS headers for utilisation of them, registration has previously failed when email addresses were provided. A workaround is omitting them. Yet they are useful for email notifications and alike, why #7 is so important.

**Comment by pierreozoux** [comment]
```
 CORS request rejected: https://matrix.allmende.io/_matrix/client/r0/account/3pid/email/requestToken 
```

**Comment by almereyda** [comment]
I have filed a more technical description of the error into https://github.com/matrix-org/synapse/issues/2914

**Comment by almereyda** [comment]
Solved by https://github.com/allmende/matrix-riot-docker/commit/a7703ec4d40fc20db1f932d1558bc829740c60e9
